from fuzzywuzzy import process

teams = ['Paris Saint Germain',
'Real Madrid',
'FC Barcelona',
'Manchester City',
'Liverpool',
'FC Bayern München',
'Manchester United',
'Atlético Madrid',
'Tottenham Hotspur',
'Al Nassr',
'Chelsea',
'Milan',
'Borussia Mönchengladbach',
'Juventus',
'Eintracht Frankfurt',
'Villarreal',
'Lazio',
'Roma',
'Inter',
'RB Leipzig',
'Borussia Dortmund',
'Celta de Vigo',
'Aston Villa',
'Sevilla',
'Real Betis',
'Los Angeles FC',
'Galatasaray',
'Newcastle United',
'Athletic Club',
'VfL Wolfsburg',
'Toronto',
'Monaco',
'Arsenal',
'Sassuolo',
'Leicester City',
'Wolverhampton Wanderers',
'Real Sociedad',
'Bayer 04 Leverkusen',
'West Ham United',
'Nice',
'Ajax',
'SC Freiburg',
'Benfica',
'Rayo Vallecano',
'Napoli',
'Atalanta',
'Palmeiras',
'Antwerp',
'Bologna',
'Olympique Lyonnais',
'Everton',
'TSG Hoffenheim',
'Sporting CP',
'Crystal Palace',
'Valencia',
'Espanyol',
'Porto',
'Getafe',
'Athletico PR',
'Anderlecht',
'Club Brugge',
'Al Shabab',
'Shanghai SIPG',
'AFC Bournemouth',
'Trabzonspor',
'Udinese',
'Southampton',
'Montpellier',
'Sporting Braga',
'Rennes',
'Lens',
'Fulham',
'Atlético Mineiro',
'Bragantino',
'Corinthians',
'Flamengo',
'Olympique Marseille',
'PSV',
'Fiorentina',
'Dinamo Zagreb',
'Salernitana',
'Lille',
'Las Palmas',
'NEC',
'Nottingham Forest',
None,
'Elche',
'Brighton & Hove Albion',
'New England',
'River Plate',
'Cádiz',
'Osasuna',
'Fluminense',
'Internacional',
'Nantes',
'Leeds United',
'Feyenoord',
'Dynamo Kyiv',
'LA Galaxy',
'Fenerbahçe',
'Strasbourg',
'FC Twente',
'Inter Miami',
'Lecce',
'Monza',
'Beşiktaş',
'Wuhan Three Towns',
'Brentford',
'Columbus Crew',
'FC Köln',
'Boca Juniors',
'Santos',
'VfB Stuttgart',
'Minnesota United',
'Empoli',
'Al Feiha',
'Parma',
'Houston Dynamo',
'Brøndby',
'Basel',
'FC Union Berlin',
'FC Augsburg',
'Rangers',
'Seattle Sounders',
'AZ',
'VfL Bochum 1848',
'Girona',
'Antalyaspor',
'Werder Bremen',
'Shakhtar Donetsk',
'Atlanta United',
'Al Hilal',
'Genk',
'Austin',
'Mallorca',
'Viktoria Plzeň',
'Racing Club',
'Nacional',
'Sampdoria',
'São Paulo',
'Reims',
'Torino',
'Slavia Praha',
'Melbourne Victory',
'İstanbul Başakşehir',
'Real Valladolid',
'Sion',
'Watford',
'Colón',
'Hellas Verona',
'Adana Demirspor',
'Levante',
'Al Ittihad',
'Hajduk Split',
'Almería',
'Nashville SC',
'Celtic',
'FSV Mainz 05',
'Philadelphia Union',
'Brest',
'Hertha BSC',
'AEK Athens',
'Fortuna Sittard',
'Vélez Sarsfield',
'Sivasspor',
'Amiens SC',
'Universidad Católica',
'Panathinaikos',
'Clermont',
'Chicago Fire',
'Fatih Karagümrük',
'København',
'PAOK',
'Lorient',
'Servette',
'Vancouver Whitecaps',
'Lugano',
'Angers SCO',
'Gil Vicente',
'Sporting Gijón',
'Independiente',
'Spezia',
'Al Wahda',
'Olimpia',
'Cremonese',
'Cincinnati',
'Daegu',
'Al Taawon',
'Toulouse',
'Ceará',
'América Mineiro',
'Gent',
'Portland Timbers',
'Middlesbrough',
'Young Boys',
'Granada',
'Godoy Cruz',
'Ajaccio',
'Salzburg',
'Union Saint-Gilloise',
'Al Ain',
'Sparta Praha',
'Genoa',
'Hangzhou',
'IFK Göteborg',
'Shandong Luneng',
'Schalke 04',
'Sporting KC',
'Real Oviedo',
'FC Utrecht',
'Changchun Yatai',
'Burnley',
'Barcelona Guayaquil',
'Norwich City',
'Deportivo Alavés',
'Atlético Nacional',
'Midtjylland',
'Westerlo',
'Hatayspor',
'Ferencváros',
'Zürich',
'West Bromwich Albion',
'Venezia',
'DC United',
'Adelaide United',
'Montreal Impact',
'Gaziantep F.K.',
'Hamburger SV',
'Melbourne City',
'Troyes',
'Shenzhen',
'Al Fateh',
'Talleres Córdoba',
'Banfield',
'Independiente del Valle',
'Lanús',
'Colo-Colo',
'SJ Earthquakes',
'SC Heerenveen',
'Bodø / Glimt',
'New York RB',
'Raków Częstochowa',
'Defensa y Justicia',
'Preston North End',
'Mamelodi Sundowns',
'Al Khaleej',
'Estudiantes',
'Sheffield United',
'Libertad',
'Atlético GO',
'Cuiabá',
'Blackburn Rovers',
'Melgar',
'Cerro Porteño',
'Dallas',
'Tigre',
'Deportivo Cali',
'Pisa',
'LDU Quito',
'Hearts',
'Huesca',
'Auxerre',
'América de Cali',
'Junior',
'Henan Jianye',
'Santa Clara',
'Zulte-Waregem',
'Caen',
'Hannover 96',
'Alanyaspor',
'Queens Park Rangers',
'Kaiserslautern',
'Al Ittifaq',
'Racing Santander',
'Huddersfield Town',
'Ankaragücü',
'SD Eibar',
'Vitória SC',
'Malmö FF',
'Dhamk',
'Guangzhou R&F',
'LASK Linz',
'Suwon Bluewings',
'AS Eupen',
'Hull City',
'FC Cartagena',
'Mechelen',
"Newell's Old Boys",
'Ñublense',
'Standard Liège',
'Al Adalh',
'Marítimo',
'Independiente Medellín',
'Al Batin',
'Charlotte',
'Vitesse',
'Rio Ave',
'Konyaspor',
'Orlando City',
'Argentinos Juniors',
'Valenciennes',
'Al Raed',
'Fortaleza',
'Cagliari',
'Kortrijk',
'Shanghai Shenhua',
'Casa Pia',
'Coventry City',
'KV Oostende',
'DSC Arminia Bielefeld',
'AGF',
'Molde',
'Ulsan',
'Como',
'Western United',
'Abha',
'Pogoń Szczecin',
'UD Ibiza',
'Paços de Ferreira',
'Kayserispor',
'Cosenza',
'Seoul',
'Sheffield Wednesday',
'Bari 1908',
'Real Zaragoza',
'Guingamp',
'Shijiazhuang Ever Bright',
'Macarthur',
'Alianza Lima',
'Saint-Étienne',
'Leganés',
'Wigan Athletic',
'Bristol City',
'Elfsborg',
'Darmstadt 98',
'Jeonbuk Motors',
'Kasımpaşa',
'Hammarby',
'Ascoli',
'Luzern',
'Djurgården',
'Swansea City',
'Frosinone',
'Atlético Tucumán',
'Real Salt Lake',
'Benevento',
'Millwall',
'Orlando Pirates',
'Sporting Charleroi',
'Vizela',
'Reggina',
'Sturm Graz',
'Karlsruher SC',
'St. Gallen',
'Burgos',
'Portimonense',
'Huracán',
'Gimnasia La Plata',
'APOEL',
'OH Leuven',
'Bordeaux',
'Metz',
'Giresunspor',
'Chengdu Qianbao',
'Nîmes',
'Nacional Asunción',
'Cercle Brugge',
'Deportes Tolima',
'Paris',
'Estoril',
'Sarmiento',
'Górnik Zabrze',
'Cienciano',
'Patronato',
'Mirandés',
'Lugo',
'Western Sydney Wanderers',
'Modena',
'Rosenborg',
'AIK',
'Rapid Vienna',
'Legia Warszawa',
'Fortuna Düsseldorf',
'Nürnberg',
'Unión Española',
'Colorado Rapids',
'Boavista',
'Jeju United',
'Palermo',
'Al Tai',
'Lech Poznań',
'Reading',
'Suwon',
'Incheon United',
'SpVgg Greuther Fürth',
'Sandhausen',
'Hibernian',
'Luton Town',
'St. Pauli',
'Stoke City',
'Piast Gliwice',
'New York City',
'Unión Santa Fe',
'Heidenheim',
'Peñarol',
'Kaizer Chiefs',
'Dijon',
'Go Ahead Eagles',
'San Lorenzo',
'Brescia',
'Sparta Rotterdam',
'Rosario Central',
'Famalicão',
'Beijing Guoan',
'SPAL',
'Gangwon',
'Sporting Cristal',
'Platense',
'Arouca',
'Sochaux',
'Paderborn',
'FCSB',
'Emelec',
'Málaga',
'Tenerife',
'Birmingham City',
'Sint-Truiden',
'Holstein Kiel',
'Norrköping',
'Vålerenga',
'Cardiff City',
'Lyngby',
'Ingolstadt',
'Sydney',
'FC Andorra',
'Peterborough United',
'Ternana',
'Magdeburg',
'AaB',
'RKC Waalwijk',
'Viking',
'Wycombe Wanderers',
'CFR Cluj',
'Hansa Rostock',
'Häcken',
'Randers',
'Chaves',
'Niort',
'Rotherham United',
'Jahn Regensburg',
'FC Volendam',
'Le Havre',
'Grasshopper',
'Universitatea Craiova',
'SSC Farul',
'Sunderland',
'Eintracht Braunschweig',
'Blackpool',
'Silkeborg',
'Villarreal II',
'Nordsjælland',
'Ponferradina',
'Hyderabad',
'Seongnam',
'Always Ready',
'Perugia',
'Lillestrøm',
'Unión La Calera',
'Annecy',
'Ümraniyespor',
'Saarbrücken',
'Wuhan Zall',
'Cracovia Kraków',
'Cittadella',
'Wisła Płock',
'1860 München',
'Tianjin Teda',
'FC Emmen',
'Caracas',
'Oxford United',
'Albacete',
'ATK Mohun Bagan',
'Barracas Central',
'Jagiellonia Białystok',
'Motherwell',
'Petrolul 52',
'Laval',
'Pohang Steelers',
'Wolfsberger AC',
'Central Cordoba SdE',
'Austria Wien',
'La Equidad',
'Meizhou Hakka',
'Plymouth Argyle',
'Mumbai City',
'Rapid Bucuresti',
'FC Groningen',
'Arsenal de Sarandi',
'Newcastle Jets',
'Delfin',
'Guaireña',
'Dundee United',
'Südtirol',
'HJK',
'Derby County',
'Erzgebirge Aue',
'Osnabrück',
'Cambridge United',
'Grenoble Foot 38',
'U Craiova 1948',
'Lechia Gdańsk',
'Goa',
'Oriente Petrolero',
'St. Johnstone',
'Ried',
'Estudiantes Mérida',
'Waldhof Mannheim',
'Aberdeen',
'OB',
'Perth Glory',
'Ipswich Town',
'Sangju Sangmu',
'The Strongest',
'Central Coast Mariners',
'Radomiak Radom',
'Strømsgodset',
'SC Cambuur',
'Barnsley',
'Excelsior',
'Wellington Phoenix',
'Rodez',
'Sepsi',
'Wanderers',
'MSV Duisburg',
'Independiente Petrolero',
'9 de Octubre',
'Royal Pari',
'Bristol Rovers',
'Cerro Largo',
'Brisbane Roar',
'Dalian Professional',
'Guangzhou Evergrande',
'Aalesund',
'Rheindorf Altach',
'İstanbulspor',
'Austria Klagenfurt',
'Hartberg',
'Bengaluru',
'Swindon Town',
'Portsmouth',
'Chennaiyin',
'Dynamo Dresden',
'Kerala Blasters',
'Wattens',
'VfB Oldenburg',
'Bolton Wanderers',
'Sarpsborg 08',
'Viborg',
'Shamrock Rovers',
'Shrewsbury Town',
'Śląsk Wrocław',
'UTA Arad',
'Charlton Athletic',
'Bastia',
'Cheltenham Town',
'Fleetwood Town',
'Odd',
'Aldosivi',
'RFC Seraing',
'Metropolitanos',
'Zagłębie Lubin',
'Deportivo Táchira',
'Deportivo La Guaira',
'Ayacucho',
'Sol de América',
'Hermanos Colmenares',
'Stockport County',
'Burton Albion',
'Quevilly Rouen',
'Helsingborg',
'Stal Mielec',
'Voluntari',
'Accrington Stanley',
'Elversberg',
'Meppen',
'Jamshedpur',
'Kalmar',
'Horsens',
'Viktoria Köln',
'Kristiansund',
'Zwickau',
'Pau',
'Odisha FC',
'Korona Kielce',
'Universitatea Cluj',
'NorthEast United',
'Exeter City',
'Wrexham',
'Freiburg II',
'Wehen Wiesbaden',
'Widzew Lodz',
'General Caballero JLM',
'Hebei CFFC',
'Hallescher FC',
'Sport Boys',
'Sandefjord',
'Ross County',
'Milton Keynes Dons',
'Rot-Weiss Essen',
'Hermannstadt',
'St. Mirren',
'Tromsø',
'Chindia Târgovişte',
'Winterthur',
'East Bengal',
'Warta Poznań',
'Guabirá',
'Wilstermann',
'Antofagasta',
'Mushuc Runa',
'Hartlepool United',
'GIF Sundsvall',
'Miedź Legnica',
'Kilmarnock',
'Stevenage',
'Bradford City',
'Haugesund',
"St Patrick's",
'Sirius',
'Port Vale',
'Northampton Town',
'Livingston',
'Morecambe',
'Degerfors',
'Derry City',
'Argeş',
'Värnamo',
'Borussia Dortmund II',
'Tranmere Rovers',
'Verl',
'Austria Lustenau',
'Botoşani',
'Carlisle United',
'Leyton Orient',
'Forest Green Rovers',
'Mansfield Town',
'Gillingham',
'Walsall',
'Lincoln City',
'Salford City',
'HamKam',
'Sutton United',
'Bayreuth',
'Varberg BoIS',
'Mioveni',
'Doncaster Rovers',
'Harrogate Town',
'Mjällby',
'AFC Wimbledon',
'Crewe Alexandra',
'Dundalk',
'Rochdale',
'Newport County',
'Colchester United',
'Barrow',
'Crawley Town',
'Bohemians',
'Jerv',
'Grimsby Town',
'Sligo Rovers',
'Finn Harps',
'Shelbourne',
'Drogheda United',
'UCD',
'Grêmio',
'Olympiakos Piraeus',
'Tigres UANL',
'América',
'Vissel Kobe',
'Monterrey',
'Atlas',
'Pumas UNAM',
'León',
'Santos Laguna',
'Atlético San Luis',
'Cruz Azul',
'Fuenlabrada',
'Al Ahli Jeddah',
'Puebla',
'Juventude',
'Guadalajara',
'Rizespor',
'Pachuca',
'Urawa Reds',
'Toluca',
'Juárez',
'Tijuana',
'Bahia',
'Chongqing Dangdai Lifan',
'Moreirense',
'Göztepe',
'Al Faisaly',
'Mazatlán',
'Cerezo Osaka',
'Necaxa',
'Vejle',
'Chapecoense',
'Kawasaki Frontale',
'Consadole Sapporo',
'Qingdao Hainiu',
'Querétaro',
'Tokyo',
'Heracles Almelo',
'Beerschot',
'Nagoya Grampus',
'Gamba Osaka',
'Gwangju',
'Kashima Antlers',
'Belenenses',
'Willem II',
'Yeni Malatyaspor',
'Tondela',
'Yokohama F. Marinos',
'Al Hazm',
'Altay',
'Nancy',
'Shimizu S-Pulse',
'Sanfrecce Hiroshima',
'Kashiwa Reysol',
'Amorebieta',
'Lausanne Sport',
'Wisła Kraków',
'Real Sociedad II',
'PEC Zwolle',
'SønderjyskE',
'Avispa Fukuoka',
'Sagan Tosu',
'Brann',
'Yokohama',
'Crotone',
'Dundee',
'Shonan Bellmare',
'Alcorcón',
'Örebro',
'Vegalta Sendai',
'Nieciecza',
'Tokushima Vortis',
'Stabæk',
'Admira',
'Dunkerque',
'Mjøndalen',
'Würzburger Kickers',
'Oita Trinita',
'Górnik Łęczna',
'Östersunds FK',
'Türkgücü-Ataspor',
'Halmstad',
'Dinamo Bucureşti',
'Gaz Metan Mediaş',
'Academica Clinceni',
'Viktoria Berlin',
'Havelse',
'Oldham Athletic',
'Scunthorpe United',
'Waterford United',
'Longford Town',
'CSKA Moskva',
'Spartak Moskva',
'Lokomotiv Moskva',
'Bolívar',
'Palestino',
'Torque',
'Universitario',
'Aucas',
'Huachipato',
'Rentistas',
'Santa Fe',
'Nacional Potosí',
'Cobresal',
'Deportivo Pasto',
'Mineros de Guayana',
'Fénix',
'UTC Cajamarca',
'Sport Huancayo',
'Guayaquil City',
'12 de Octubre',
'Macará',
'Municipal Vinto',
'Carlos Manucci',
'Aragua',
'Academia Puerto Cabello',
'Junior FC',
'Club Atlético Lanús',
'Club Deportivo Jorge Wilstermann',
'IFK Norrköping',
'Club Deportivo Guabirá',
'Cerro Largo Fútbol Club',
'New York City FC',
'Clube Sport Marítimo',
'Wuhan FC',
'Strømsgodset IF',
'FC Schalke 04',
'Barcelona Sporting Club',
'1. FSV Mainz 05',
'Henan Songshan Longmen FC',
'TSV 1860 München',
'HJK Helsinki',
'Viborg FF',
'Shandong Taishan',
'Changchun Yatai FC',
'New York Red Bulls',
'AFC UTA Arad',
'Daegu FC',
'Shijiazhuang Ever Bright F.C.',
'Shanghai Shenhua FC',
'Unión Deportiva Almería',
'Club Nacional',
'Guaireña FC',
'CD Antofagasta',
'Deportivo La Guaira FC',
'Seongnam FC',
'Aarhus GF',
'Bruk-Bet Termalica Nieciecza',
'FC Vizela',
'Oud-Heverlee Leuven',
'Mazatlán Futbol Club',
'KSV Cercle Brugge',
'Paris FC',
'AZ Alkmaar',
'FC Farul Constanța',
'U.C. Sampdoria',
'Dijon FCO',
'Standard de Liège',
'Toulouse Football Club',
'FC Cincinnati',
'Tromsø IL',
'FC Nordsjælland',
'RCD Mallorca',
'Jeju United FC',
'Shanghai Port FC',
'Gangwon FC',
'FBC Melgar',
'Metropolitanos de Caracas FC',
'Suwon FC',
'CD Mirandés',
'New England Revolution',
'Club León',
'CD Lugo',
'Guangzhou City',
'FC Midtjylland',
'FK Haugesund',
'AD Alcorcón',
'Rosenborg BK',
'SC East Bengal FC',
'Chamois Niortais Football Club',
'Macarthur FC',
'Seattle Sounders FC',
'USL Dunkerque',
'Orlando City Soccer Club',
'FC Lausanne-Sport',
'FC Viktoria Plzeň',
'SK Slavia Praha',
'Sporting Kansas City',
'Portimonense SC',
'Club Deportivo Guadalajara',
'Vitória de Guimarães',
'Urawa Red Diamonds',
'KRC Genk',
'Atakaş Hatayspor',
'Toronto FC',
'SK Rapid Wien',
'RZ Pellets Wolfsberger AC',
'Club Tijuana',
'Minnesota United FC',
'Lillestrøm SK',
'Inter Miami CF',
'1. FC Saarbrücken',
'Vancouver Whitecaps FC',
'Club Atlético Banfield',
'Club Universitario de Deportes',
'Villarreal CF',
'Deportivo Táchira FC',
'AC Sparta Praha',
'Club Atlético Talleres',
'SV Ried',
'Arsenal de Sarandí',
'SC Braga',
'San Lorenzo de Almagro',
'Sint-Truidense VV',
'KAA Gent',
'FC Lugano',
'Club Universidad Nacional',
'San Jose Earthquakes',
'Bohemian FC',
'FC Voluntari',
'Sydney FC',
'Guangzhou FC',
'FC Dallas',
'Grasshopper Club Zürich',
'GwangJu FC',
'Club The Strongest',
'FC Seoul',
'Club Olimpia',
'Club Bolívar',
'Club Deportivo Palestino',
'Club Atlético Sarmiento',
'FC Sion',
'Belenenses SAD',
'Damac FC',
'Club Atlético Independiente',
'APOEL Nicosia FC',
'Ferencvárosi TC',
'Club Atlético Palmaflor',
'Club Deportes Tolima',
'CS Emelec',
'Club Atlético Peñarol',
'Club Atlético Aldosivi',
'Montevideo City Torque',
'Beşiktaş JK',
'Unión de Santa Fe',
'Stade de Reims',
'FC Botoşani',
'FC Flyeralarm Admira',
'CD Leganés',
'FC Academica Clinceni',
'IK Sirius',
'Club Necaxa',
'Aytemiz Alanyaspor',
'CS Mioveni',
'Djurgårdens IF',
'Seraing',
'AC Monza',
'Servette FC',
'Club Atlético Rentistas',
'Club Independiente Santa Fe',
'Club Always Ready',
'Vejle Boldklub',
'Club Libertad',
'SL Benfica',
'Fútbol Club Juárez',
'Centro Atlético Fénix',
'FC Paços de Ferreira',
'AC Milan',
'Club Social y Deportivo Macará',
'Guayaquil City FC',
'Club Atlético Nacional Potosí',
'Sandefjord Fotball',
'US Salernitana 1919',
'Carlos A. Mannucci',
'Aragua Fútbol Club',
'FC Viktoria 1889 Berlin',
'Vålerenga Fotball',
'CD Huachipato',
'AC Mineros de Guayana',
'Campionii FC Arges',
'Degerfors IF',
'Estudiantes de La Plata',
'FC St. Gallen 1879',
'CF Fuenlabrada',
'Viking FK',
'Mjällby AIF',
'BSC Young Boys',
'Dundee FC',
'SV Darmstadt 98',
'FC Basel 1893',
'Wrexham AFC',
'Ulsan Hyundai FC',
'Hebei FC',
'GZT Giresunspor',
'Kasimpaşa SK',
'N.E.C. Nijmegen',
'FC Girondins de Bordeaux',
'Granada CF',
'Cádiz CF',
'FC Arouca',
'Getafe CF',
'Olympiacos CFP',
'Incheon United FC',
'SV Sandhausen',
'SC Rheindorf Altach',
'CD Tondela',
'Club Atlético Huracán',
'Sociedad Deportiva Aucas',
'Cracovia',
'Valenciennes FC',
'Kalmar FF',
'PGE FKS Stal Mielec',
'WSG Tirol',
'Gil Vicente FC',
'FSV Zwickau',
'SV Meppen',
'Odense Boldklub',
'Torino F.C.',
'Club Atlético Central Córdoba',
'ESTAC Troyes',
'Valencia CF',
'FC Tokyo',
'K Beerschot VA',
'Panathinaikos FC',
'Randers FC',
'Varbergs BoIS FC',
'Rodez Aveyron Football',
'Chicago Fire Football Club',
'Sportclub Verl',
'Shenzhen FC',
'Aalborg BK',
'Al Hazem',
'Molde FK',
'Stade Malherbe Caen',
'D.C. United',
'Chennaiyin FC',
'AS Saint-Étienne',
'FC Metz',
'NorthEast United FC',
'AC Ajaccio',
'FC Ingolstadt 04',
'FC Lokomotiv Moscow',
'Real Valladolid CF',
'AS Monaco',
'Galatasaray SK',
'1. FC Magdeburg',
'VfL Osnabrück',
'FC Luzern',
'Suwon Samsung Bluewings',
'Gimnasia y Esgrima La Plata',
'Racing Club de Lens',
'Elche CF',
'1. FC Heidenheim 1846',
'Jeonbuk Hyundai Motors',
'FK Austria Wien',
'SSV Jahn Regensburg',
'En Avant de Guingamp',
'Brøndby IF',
'Royal Charleroi S.C.',
'FC Zürich',
"St. Patrick's Athletic",
'Austin FC',
'Silkeborg IF',
'ATK Mohun Bagan FC',
'Abha Club',
'AFC Chindia Târgoviște',
'Sepsi OSK Sf. Gheorghe',
'Al Ahli',
'RCD Espanyol de Barcelona',
'Club Atlético de San Luis',
'Gallos Blancos de Querétaro',
'12 de Octubre FC',
'Club River Plate Asunción',
'KV Kortrijk',
'TSV Egger Glas Hartberg',
'Rapid București',
'U.S. Sassuolo Calcio',
'FC Porto',
'TSV Havelse',
'OGC Nice',
'FC Dinamo 1948 Bucureşti',
'Livingston FC',
'Girona FC',
'SC Freiburg II',
'FC Red Bull Salzburg',
'Demir Grup Sivasspor',
'Odds BK',
'BK Häcken',
'KAS Eupen',
'St. Johnstone FC',
'Türkgücü München',
'Dalian Professional Football Club',
'Club de Deportes Cobresal',
'Club Nacional de Football',
'Universidad Técnica de Cajamarca',
'1. FC Kaiserslautern',
'FK Bodø/Glimt',
'Deportivo Toluca',
'SC Bastia',
'Fenerbahçe SK',
'Puebla FC',
'Levante Unión Deportiva',
'Real Madrid CF',
'Göztepe SK',
'Club Brugge KV',
'RC Celta de Vigo',
'SK Austria Klagenfurt',
'Athletic Club de Bilbao',
'Real Sociedad B',
'Gazişehir Gaziantep F.K.',
'Altay SK',
'Hammarby IF',
'Atlético de Madrid',
'SD Huesca',
'Club de Foot Montréal',
'Kristiansund BK',
'IF Elfsborg',
'RSC Anderlecht',
'Heart of Midlothian',
'Tianjin Jinmen Tiger FC',
'FCSB Steaua)',
'FC St. Pauli',
'FC Goa',
'Dundalk FC',
'Royale Union Saint-Gilloise',
'Beijing Guoan FC',
'Waterford FC',
'Qingdao FC',
'Chongqing Liangjiang Athletic',
'Málaga CF',
'SV Werder Bremen',
'İttifak Holding Konyaspor',
'Le Havre AC',
'1. FC Köln',
'Clermont Foot 63',
'Real Sporting de Gijón',
'Unión Deportiva Las Palmas',
'FC Lorient',
'Mumbai City FC',
'Bengaluru FC',
'Club América',
'Kerala Blasters FC',
'Western United FC',
'Stade Brestois 29',
'FC Erzgebirge Aue',
'F.C. København',
'SK Sturm Graz',
'Stade Rennais FC',
'CF Monterrey',
'Al Taawoun',
'Venezia FC',
'Club Atlas',
'Yokohama FC',
'AJ Auxerre',
'Pau FC',
'Jamshedpur FC',
'Boavista FC',
'Associação Chapecoense de Futebol',
'Tigres U.A.N.L.',
'FC U Craiova 1948',
'US Quevilly Rouen Métropole',
'FC Würzburger Kickers',
'Sarpsborg 08 FF',
'CD Tenerife',
'Sevilla FC',
'Melbourne City FC',
'SD Ponferradina',
'SK Brann',
'Montpellier Hérault SC',
'Royal Antwerp FC',
'Paris Saint-Germain',
'Real Betis Balompié',
'PFC CSKA Moscow',
'RB Bragantino',
'LOSC Lille',
'Olympique de Marseille',
'1. FC Union Berlin',
'İstanbul Başakşehir FK',
'Clube Atlético Mineiro',
'Sport Club Corinthians Paulista',
'Fatih Karagümrük S.K.',
'Udinese Calcio',
'Sport-Club Freiburg',
'CA Osasuna',
'RC Strasbourg Alsace',
'FC Nantes',
'Rangers FC',
'Nîmes Olympique',
'Club Atlético Colón',
'Ceará Sporting Club',
'Club Athletico Paranaense',
'Club Cerro Porteño',
'Moreirense FC',
'Ettifaq FC',
'Atlético Clube Goianiense',
'Çaykur Rizespor',
'Al Ain FC',
'SV Zulte Waregem',
'Yukatel Kayserispor',
'Al Fayha',
'Futebol Clube de Famalicão',
'Hokkaido Consadole Sapporo',
'1. FC Nürnberg',
'KV Mechelen',
'SC Paderborn 07',
'Estoril Praia',
'SD Amorebieta',
'Club Sporting Cristal',
'FC Sochaux-Montbéliard',
'Burgos CF',
'AS Nancy Lorraine',
'F.C. Hansa Rostock',
'SG Dynamo Dresden',
'Örebro SK',
'SV Waldhof Mannheim 07',
'Hyderabad FC',
'Mjøndalen IF',
'Halmstads BK',
'Stabæk Fotball',
'SV Wehen Wiesbaden',
'Ross County FC',
'Coritiba',
'Botafogo',
'Gençlerbirliği',
'Chievo',
'Farense',
'ADO Den Haag',
'Al Quadisiya',
'Goiás',
'Royal Excel Mouscron',
'Denizlispor',
'Castellón',
'BB Erzurumspor',
'Waasland-Beveren',
'VVV-Venlo',
'UD Logroñés',
'Sabadell',
'Astra',
"Busan I'Park",
'Viitorul',
'Chambly',
'Start',
'Châteauroux',
'Unterhaching',
'St. Pölten',
'Jiangsu Suning',
'Uerdingen',
'Bayern München II',
'Podbeskidzie',
'VfB Lübeck',
'Hamilton Academical',
'Vaduz',
'Falkenberg',
'CSM Iaşi',
'Southend United',
'Cork City',
'Vasco da Gama',
'El Nacional',
'Millonarios',
'Deportivo Binacional',
'Guaraní',
'Real Garcilaso',
'Audax Italiano',
'Coquimbo Unido',
'Plaza Colonia',
'Atlético Grau',
'Sportivo Luqueño',
'Zamora Fútbol Club',
'Blooming',
'Llaneros de Guanare',
'Club Plaza de Deportes Colonia',
'Liverpool Fútbol Club',
'AFC Astra Giurgiu',
'Chievo Verona',
'Hamilton Academical FC',
'Lyngby BK',
'KFC Uerdingen 05',
'Club Sportivo Luqueño',
'Podbeskidzie Bielsko-Biała',
'Club Sol de América',
'AFC Hermannstadt',
'Helsingborgs IF',
'Club Atlético River Plate',
'CSM Politehnica Iași',
'Caracas Fútbol Club',
'AC Horsens',
'Gençlerbirliği SK',
'FC Bayern München II',
'spusu SKN St. Pölten',
'FC Viitorul Constanța',
'CD Nacional',
'C.D. Castellón',
'SpVgg Unterhaching',
'MKE Ankaragücü',
'Al Wehda',
'Falkenbergs FF',
'CE Sabadell FC',
'Albacete BP',
'Jiangsu FC',
'Delfín Sporting Club',
'Al Adalah',
'Estudiantes de Mérida',
'Rio Ave FC',
'Club de Regatas Vasco da Gama',
'Club Guaraní',
'Millonarios FC',
'Club Deportivo El Nacional',
'Sangju Sangmu FC',
'SC Farense',
'Club Atlético Grau',
'Club Atlético Tigre',
'La Berrichonne de Châteauroux',
'Cusco Fútbol Club',
'Club Alianza Lima',
'Club Deportivo Oriente Petrolero',
'FC Chambly Oise',
'C.D. Universidad Católica del Ecuador',
'IK Start',
'Busan IPark',
'Club Social, Cultural y Deportivo de Blooming',
'Aalesunds FK',
'FC Vaduz',
'Llaneros de Guanare Escuela de Fútbol',
'Shelbourne FC',
'Cruzeiro',
'CSA',
'Beijing Renhe',
'Vitória FC',
'Avaí',
'Neuchâtel Xamax',
'Morelia',
'Unión Magdalena',
'Tianjin Quanjian',
'Desportivo Aves',
'Universidad Chile',
'Deportivo La Coruña',
'Once Caldas',
'Esbjerg',
'Pescara',
"O'Higgins",
'Numancia',
'Thun',
'Virtus Entella',
'Pordenone',
'Extremadura UD',
'Gyeongnam',
'Deportes Iquique',
'Livorno',
'Rionegro Águilas',
'Veracruz',
'Orléans',
'Trapani',
'Arka Gdynia',
'Le Mans',
'Cúcuta Deportivo',
'Carl Zeiss Jena',
'Atlético Huila',
'Envigado',
'Juve Stabia',
'Curicó Unido',
'Atlético Bucaramanga',
'Jaguares de Córdoba',
'Hobro',
'Univ. Concepción',
'Patriotas Boyacá',
'ŁKS Łódź',
'Ranheim',
'Júbilo Iwata',
'Chemnitzer FC',
'Alianza Petrolera',
'Mattersburg',
'Matsumoto Yamaga',
'Sonnenhof Großaspach',
'Preußen Münster',
'AFC Eskilstuna',
'Macclesfield Town',
'Bury',
'Beijing Renhe FC',
'Centro Sportivo Alagoano',
'Tianjin Quanjian FC',
'Avaí FC',
'Deportivo de La Coruña',
'Desportivo das Aves',
'Neuchâtel Xamax FCS',
'Club Unión Magdalena S.A',
'Monarcas Morelia',
'CD Everton de Viña del Mar',
'Universidad de Chile',
'US Cremonese',
'Vitória de Setúbal',
'FC Thun',
'Tiburones Rojos de Veracruz',
'Virtus Entella Chiavari',
'Gyeongnam FC',
'CD Universidad de Concepción',
'Castellammare di Stabia',
"CD O'Higgins",
'CD Numancia',
'Envigado FC',
'Patriotas Boyacá FC',
'Jaguares de Córdoba Fútbol Club',
'Le Mans FC',
'Hobro IK',
'Esbjerg fB',
'Ranheim Fotball',
'SG Sonnenhof Großaspach',
'Matsumoto Yamaga FC',
'SV Mattersburg',
'SC Preußen Münster',
'US Orléans Loiret Football',
'FC Carl Zeiss Jena',
'UCD AFC',
'Akhisar Belediyespor',
'Vitória',
'Sport Recife',
'Paraná',
'Bursaspor',
'Lobos BUAP',
'Padova',
'Foggia',
'Feirense',
'Belgrano',
'Guizhou Zhicheng',
'San Martín San Juan',
'NAC Breda',
'Gimnàstic Tarragona',
'San Martín Tucumán',
'Carpi',
'Lokeren',
'Rayo Majadahonda',
'Córdoba',
'San Luis',
'Ohod',
'Gazélec Ajaccio',
'Béziers',
'Jeonnam Dragons',
'Deportes Temuco',
'V-Varen Nagasaki',
'De Graafschap',
'Red Star',
'Aalen',
'Vendsyssel',
'Wacker Innsbruck',
'Energie Cottbus',
'Fortuna Köln',
'Sportfreunde Lotte',
'Zagłębie Sosnowiec',
'Notts County',
'Boyacá Chicó',
'Leones FC',
'Trelleborg',
'Dalkurd',
'Yeovil Town',
'Brommapojkarna',
'Reus Deportiu',
'Limerick',
'Bray Wanderers',
'Vendsyssel FF',
'San Martín de San Juan',
'Gimnàstic de Tarragona',
'San Luis de Quillota',
'CF Reus Deportiu',
'Itagüí Leones FC',
'FC Energie Cottbus',
'IF Brommapojkarna',
'Belgrano de Córdoba',
'Club Deportes Temuco',
'GD Chaves',
'Sporting Lokeren',
'Córdoba CF',
'CD Feirense',
'AS Béziers',
'Boyacá Chicó FC',
'San Martin de Tucumán',
'GFC Ajaccio',
'Ohod Club',
'Limerick FC',
'América Futebol Clube',
'Guizhou Zhicheng FC',
'Sport Club do Recife',
'Al Qadisiyah',
'CF Rayo Majadahonda',
'Red Star FC',
'VfR Aalen',
'SC Fortuna Köln',
'FC Wacker Innsbruck',
'VfL Sportfreunde Lotte',
'Dalkurd FF',
'Trelleborgs FF',
'Cesena',
'Bari',
'Avellino',
'Zenit',
'Krasnodar',
'Rubin Kazan',
'Ufa',
'Arsenal Tula',
'Osmanlıspor',
'Ural',
'Ponte Preta',
'Akhmat Grozny',
'Dinamo Moskva',
'Rostov',
'Cultural Leonesa',
'Barcelona II',
'Tosno',
'Anzhi',
'Cortuluá',
'Pro Vercelli',
'Karabükspor',
'Novara',
'Omiya Ardija',
'SKA Khabarovsk',
'Amkar Perm',
'Santiago Wanderers',
'Lorca',
'Roda JC Kerkrade',
'Tours',
'Bourg-en-Bresse',
'Sevilla II',
'Olimpo',
'Chacarita Juniors',
'Sandecja Nowy Sącz',
'Temperley',
'Ventforet Kofu',
'Sogndal',
'Rot-Weiß Erfurt',
'Jönköpings Södra',
'Tigres',
'Partick Thistle',
'Werder Bremen II',
'Barnet',
'Chesterfield',
'FC Helsingør',
'Albirex Niigata',
'Galway United',
"Rubin Kazan'",
"Amkar Perm'",
'Zenit St. Petersburg',
'FC Krasnodar',
'FC Ufa',
'Dinamo Moscow',
'FC Rostov',
'Terek Grozny',
'Kardemir Karabükspor',
'FC Anzhi Makhachkala',
'FC Ural Yekaterinburg',
'FC Tosno',
'FC Pro Vercelli 1892',
'Novara Calcio',
'FC Barcelona B',
'Club Olimpo',
'Football Bourg En Bresse Peronnas 01',
'Sevilla Atlético',
'Tours FC',
'Club Atlético Temperley',
'Lorca FC',
'Sogndal Fotball',
'FC Rot-Weiß Erfurt',
'Jönköpings Södra IF',
'Partick Thistle FC',
'SV Werder Bremen II',
'Tigres FC',
'Ankaraspor',
'Orenburg',
'Figueirense',
'Criciúma',
'Joinville',
'Santa Cruz',
'Krylya Sovetov',
'Gaziantepspor',
'Adanaspor',
'Chiapas',
'Quilmes',
'UCAM Murcia',
'Latina',
'Vicenza',
"Tom' Tomsk",
'Inverness CT',
'Atlético Rafaela',
'Ruch Chorzów',
'Fortaleza CEIF',
'Gefle',
'Wexford Youths',
'Atlético de Rafaela',
'Stade Lavallois Mayenne FC',
'Jaguares de Chiapas',
'Quilmes Atlético Club',
'Krylya Sovetov Samara',
'FC Orenburg',
'UCAM Murcia CF',
'FC Tom Tomsk',
'Inverness Caledonian Thistle',
'KVC Westerlo',
'Gefle IF',
"Kuban' Krasnodar",
'União Madeira',
'Mersin İdman yurdu',
'Eskişehirspor',
'Athletic Club II',
'FSV Frankfurt',
'Académica',
'Mordovia Saransk',
'Dorados',
'Evian TG',
'Virtus Lanciano',
'Llagostera-Costa Brava',
'Nueva Chicago',
'San Marcos',
'Najran',
'Créteil',
'Hajer',
'Crucero del Norte',
'Daejeon Citizen',
'Uniautonoma',
'Dagenham & Redbridge',
'Grödig',
'Åtvidaberg',
'York City',
'FC Mordovia Saransk',
'Mersin İdman Yurdu',
'Dorados de Sinaloa',
'Dagenham and Redbridge',
'Évian Thonon Gaillard FC',
'Kuban Krasnodar',
'SS Virtus Lanciano',
'União da Madeira',
'Najran SC',
'UE Llagostera',
'SV Grödig',
'Deportivo San Marcos de Arica',
'US Créteil-Lusitanos',
'Uniautónoma FC',
'Athletic Club de Bilbao B',
'Associação Académica de Coimbra',
'Åtvidabergs FF',
'Catania',
'Torpedo Moskva',
'Kayseri Erciyesspor',
'Balıkesirspor',
'Penafiel',
'Recreativo Huelva',
'Arles',
'Universidad Guadalajara',
'Lierse',
'Al Orubah',
'Varese',
'FC Dordrecht',
'Vestsjaelland',
'Cobreloa',
'Zawisza Bydgoszcz',
'Chivas USA',
'Bełchatów',
'Aarau',
'Al Shoalah',
'Sandnes Ulf',
'Wiener Neustadt',
'Barnechea',
'Athlone Town',
'AC Arles Avignon',
'AC Barnechea',
'Torpedo Moscow',
'Al Orobah',
'CD Cobreloa',
'Leones Negros de la UdeG',
'RC Recreativo de Huelva',
'Lierse SK',
'GKS Bełchatów',
'Al Shoulla',
'FC Penafiel',
'SC Magna Wiener Neustadt',
'FC Vestsjælland',
'Deportivo Ñublense',
'FC Aarau']


def fix_outliers(team_name):
    if team_name == "Man Utd":
        return "Manchester United"
    return team_name
    
def find_most_similar(team_name):
    highest = process.extractOne(fix_outliers(team_name), teams)
    return highest[0]  # Returns the most similar team name

